name: Continous Integration and Deployment for BY

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true

      - name: Build the app with dotnet
        run: dotnet build --configuration Release

      - name: Publish app
        run: dotnet publish --configuration Release -o ./out

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
           app-name: 'bydevops'
           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AEAE34D5F39240529592C951F6A8F01B }}
           package: ./out